2022-03-24 14:16:55,063 INFO    MainThread:19960 [wandb_setup.py:_flush():70] setting env: {}
2022-03-24 14:16:55,063 INFO    MainThread:19960 [wandb_setup.py:_flush():70] multiprocessing start_methods=spawn
2022-03-24 14:16:55,063 INFO    MainThread:19960 [wandb_setup.py:_flush():70] setting login settings: {}
2022-03-24 14:16:55,063 INFO    MainThread:19960 [wandb_init.py:_log_setup():318] Logging user logs to C:\PyTorch_YOLOv4\wandb\run-20220324_141655-d2kgi8fq\logs\debug.log
2022-03-24 14:16:55,064 INFO    MainThread:19960 [wandb_init.py:_log_setup():319] Logging internal logs to C:\PyTorch_YOLOv4\wandb\run-20220324_141655-d2kgi8fq\logs\debug-internal.log
2022-03-24 14:16:57,121 INFO    MainThread:19960 [wandb_run.py:_console_start():1396] atexit reg
2022-03-24 14:16:57,122 INFO    MainThread:19960 [wandb_run.py:_redirect():1259] redirect: SettingsConsole.WRAP
2022-03-24 14:16:57,122 INFO    MainThread:19960 [wandb_run.py:_redirect():1294] Wrapping output streams.
2022-03-24 14:16:57,122 INFO    MainThread:19960 [wandb_run.py:_redirect():1310] Redirects installed.
2022-03-24 14:17:44,476 INFO    MainThread:19960 [wandb_run.py:_atexit_cleanup():1366] got exitcode: 1
2022-03-24 14:17:44,476 INFO    MainThread:19960 [wandb_run.py:_restore():1338] restore
2022-03-24 14:17:44,737 INFO    MainThread:19960 [wandb_run.py:_wait_for_finish():1489] got exit ret: file_counts {
  wandb_count: 1
  media_count: 2
}
pusher_stats {
  uploaded_bytes: 751452
  total_bytes: 751452
}

2022-03-24 14:17:46,748 INFO    MainThread:19960 [wandb_run.py:_wait_for_finish():1489] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
  media_count: 2
}
pusher_stats {
  uploaded_bytes: 766242
  total_bytes: 766242
}

2022-03-24 14:17:47,836 INFO    MainThread:19960 [wandb_run.py:_show_summary():1644] rendering summary
2022-03-24 14:17:47,837 INFO    MainThread:19960 [wandb_run.py:_show_history():1682] rendering history
2022-03-24 14:17:47,838 INFO    MainThread:19960 [wandb_run.py:_show_files():1711] logging synced files
2022-03-24 14:17:47,841 INFO    MainThread:19960 [internal.py:handle_exit():139] Internal process exited
